Add back improvements to CI testing

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,18 +1,264 @@
+sudo: false
+
+cache:
+  directories:
+    - $HOME/cache
+    - $HOME/.cpan/sources
+
 language: perl
+
 perl:
+  - "5.8.1"
   - "5.8"
   - "5.10"
+  - "5.12.0"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"
+  - "5.18-shrplib"
   - "5.20"
+  - "5.20-shrplib"
   - "5.22"
+  - "5.22-shrplib"
   - "5.24"
+  - "5.24-shrplib"
+  - "5.26"
+
+matrix:
+  include:
+    - perl: "5.20"
+      env: DB=MySQL VERSION=4.1.22
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.0.15
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.0.96
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.1.30
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.1.72
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.5.8
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.5.47
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.5.49
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.5.54
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.5.55
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.5.56
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.6.10
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.6.30
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.6.35
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.6.36
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.7.8-rc
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.7.11
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.7.12
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.7.17
+    - perl: "5.20"
+      env: DB=MySQL VERSION=5.7.18
+    - perl: "5.20"
+      env: DB=MySQL VERSION=8.0.0-dmr
+    - perl: "5.20"
+      env: DB=MySQL VERSION=8.0.1-dmr
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=5.5.40
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=5.5.44
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=5.5.47
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=5.5.54
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=5.5.55
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.0.14
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.0.20
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.0.23
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.0.29
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.0.30
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.0.31
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.1.2
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.1.8
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.1.11
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.1.20
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.1.22
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.1.24
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.2.0
+    - perl: "5.20"
+      env: DB=MariaDB VERSION=10.2.1
+# Incompatible with DBD::mysql due to broken mysql_config
+#    - perl: "5.20"
+#      env: DB=MariaDB VERSION=10.2.2
+#    - perl: "5.20"
+#      env: DB=MariaDB VERSION=10.2.3
+# Incompatible with DBD::mysql due to broken something in libmysqlclient
+#    - perl: "5.20"
+#      env: DB=MariaDB VERSION=10.2.4
+#    - perl: "5.20"
+#      env: DB=MariaDB VERSION=10.2.5
+# Not supported by MySQL::Sandbox yet
+#    - perl: "5.20"
+#      env: DB=MariaDB VERSION=10.3.0
+    - perl: "5.20"
+      env: CONC_DB=MySQL CONC_VERSION=6.0.0-beta
+    - perl: "5.20"
+      env: CONC_DB=MySQL CONC_VERSION=6.0.2
+    - perl: "5.20"
+      env: CONC_DB=MySQL CONC_VERSION=6.1.0
+    - perl: "5.20"
+      env: CONC_DB=MySQL CONC_VERSION=6.1.9
+    - perl: "5.20"
+      env: CONC_DB=MySQL CONC_VERSION=6.1.10
+    - perl: "5.20"
+      env: CONC_DB=MySQL CONC_VERSION=6.2.0-labs
+# Incompatible with DBD::mysql due to broken zerofill support
+#    - perl: "5.20"
+#      env: CONC_DB=MariaDB CONC_VERSION=2.2.0
+#    - perl: "5.20"
+#      env: CONC_DB=MariaDB CONC_VERSION=2.2.3
+#    - perl: "5.20"
+#      env: CONC_DB=MariaDB CONC_VERSION=2.3.0
+#    - perl: "5.20"
+#      env: CONC_DB=MariaDB CONC_VERSION=2.3.2
+#    - perl: "5.20"
+#      env: CONC_DB=MariaDB CONC_VERSION=3.0.1-beta
+
+addons:
+  apt:
+    packages:
+      - libaio-dev
+      - libnuma-dev
+      - libjemalloc-dev
+      - libmysqlclient-dev
+      - libmysqld-dev
+      - libwrap0-dev
+      - libstdc++5
+
 before_install:
- - sudo apt-get update -qq
- - sudo apt-get install -qq libmysqlclient-dev libmysqld-dev libwrap0-dev
- - perlbrew install-cpanm -f
+  - if [ -z "$PERLBREW_PERL" ]; then eval $(curl https://travis-perl.github.io/init) --perl; fi
+  - if [ "$DB" = "MySQL" ]; then
+      case "$VERSION" in
+        4.1.*)            SANDBOX_URL=http://mysql.localhost.net.ar/Downloads/MySQL-4.1/mysql-standard-$VERSION-unknown-linux-gnu-x86_64-glibc23.tar.gz ;;
+        5.0.[012]*)       SANDBOX_URL=https://downloads.mysql.com/archives/get/file/mysql-standard-$VERSION-linux-x86_64-glibc23.tar.gz ;;
+        5.[01].*)         SANDBOX_URL=https://downloads.mysql.com/archives/get/file/mysql-$VERSION-linux-x86_64-glibc23.tar.gz ;;
+        5.5.?)            SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux2.6-x86_64.tar.gz ;;
+        5.5.[1234]*)      SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux2.6-x86_64.tar.gz ;;
+        5.5.5[012345]*)   SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux2.6-x86_64.tar.gz ;;
+        5.[567].*)        SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.5-x86_64.tar.gz ;;
+        8.0.*)            SANDBOX_URL=https://dev.mysql.com/get/mysql-$VERSION-linux-glibc2.12-x86_64.tar.gz ;;
+        *)                echo "Unsupported MySQL version '$VERSION'"; exit 1 ;;
+      esac ;
+      SANDBOX_CACHE_FILE="$HOME/cache/$(basename "$SANDBOX_URL")" ;
+    elif [ "$DB" = "MariaDB" ]; then
+      SANDBOX_URL=https://downloads.mariadb.com/MariaDB/mariadb-$VERSION/bintar-linux-x86_64/mariadb-$VERSION-linux-x86_64.tar.gz ;
+      SANDBOX_CACHE_FILE="$HOME/cache/mariadb-$VERSION-linux-x86_64.tar.gz" ;
+    elif [ -n "$DB" ]; then
+      echo "Unsupported DB '$DB'"; exit 1 ;
+    fi
+  - if [ -n "$DB" ]; then
+      export SANDBOX_HOME="$HOME/sandbox" ;
+      export SANDBOX_BINARY="$SANDBOX_HOME/binary" ;
+      export SANDBOX_FILE="$SANDBOX_HOME/$(basename "$SANDBOX_CACHE_FILE")" ;
+      if [ ! -f "$SANDBOX_CACHE_FILE" ]; then wget "$SANDBOX_URL" -O "$SANDBOX_CACHE_FILE" || exit 1; fi ;
+      mkdir -p "$SANDBOX_HOME" || exit 1 ;
+      ln -s "$SANDBOX_CACHE_FILE" "$SANDBOX_FILE" || exit 1 ;
+    fi
+  - if [ "$CONC_DB" = "MySQL" ]; then
+      case "$CONC_VERSION" in
+        *-labs)           CONC_URL=https://downloads.mysql.com/snapshots/pb/mysql-connector-c-$CONC_VERSION/mysql-connector-c-$CONC_VERSION-linux-glibc2.5-x86_64.tar.gz ;;
+        6.0.*)            CONC_URL=https://dev.mysql.com/get/mysql-connector-c-$CONC_VERSION-linux-glibc2.3-x86-64bit.tar.gz ;;
+        6.1.[0123456789]) CONC_URL=https://dev.mysql.com/get/mysql-connector-c-$CONC_VERSION-linux-glibc2.5-x86_64.tar.gz ;;
+        6.1.*)            CONC_URL=https://dev.mysql.com/get/mysql-connector-c-$CONC_VERSION-linux-glibc2.12-x86_64.tar.gz ;;
+        *)                echo "Unsupported MySQL Connector/C version '$VERSION'"; exit 1 ;;
+      esac ;
+      CONC_FILE="$HOME/cache/$(basename "$CONC_URL")" ;
+    elif [ "$CONC_DB" = "MariaDB" ]; then
+      CONC_URL=https://downloads.mariadb.com/Connectors/c/connector-c-${CONC_VERSION/-*/}/mariadb-connector-c-$CONC_VERSION-linux-x86_64.tar.gz ;
+      CONC_FILE="$HOME/cache/mariadb-connector-c-$CONC_VERSION-linux-x86_64.tar.gz" ;
+    elif [ -n "$CONC_DB" ]; then
+      echo "Unsupported Connector/C '$CONC_DB'"; exit 1 ;
+    fi
+  - if [ -n "$CONC_DB" ]; then
+      if [ ! -f "$CONC_FILE" ]; then wget "$CONC_URL" -O "$CONC_FILE" || exit 1; fi ;
+    fi
+
 install:
-  - cpanm --quiet DBI Test::Pod Test::Deep Test::DistManifest Proc::ProcessTable
-script: "export RELEASE_TESTING=1 && perl Makefile.PL && make disttest && perl Makefile.PL --force-embedded && make disttest"
+  - perlbrew install-cpanm --force --notest
+  - cpanm --quiet --notest --skip-satisfied DBI Devel::CheckLib
+  - cpanm --quiet --notest --skip-satisfied --installdeps --with-configure --with-develop --with-recommends --with-suggests .
+  - if [ -n "$DB" ]; then
+      cpanm --quiet --notest --skip-satisfied MySQL::Sandbox || exit 1 ;
+      make_sandbox --export_binaries "$SANDBOX_FILE" -- --sandbox_port 3310 --sandbox_directory msb --no_confirm || exit 1 ;
+      mysqladmin -u root shutdown || exit 1 ;
+    fi
+  - if [ -n "$CONC_DB" ]; then
+      mkdir -p "$HOME/conc" ;
+      tar --strip-components=1 --directory="$HOME/conc" -xf "$CONC_FILE" || exit 1 ;
+      if $HOME/conc/bin/mysql_config 2>&1 | grep -q /usr/local; then
+        rm -f $HOME/conc/bin/mysql_config ;
+      fi ;
+      if [ -x $HOME/conc/bin/mysql_config ]; then
+        sed 's/-l "/-lmysqlclient "/g' -i "$HOME/conc/bin/mysql_config" || exit 1 ;
+      else
+        INCLUDE_PATH=`find "$HOME/conc" -name "mysql.h" | sort | head -1` ;
+        if [ -z "$INCLUDE_PATH" ]; then echo "File mysql.h was not found"; exit 1; fi ;
+        LIB_PATH=`find "$HOME/conc" -name "lib*.so" | sort | head -1` ;
+        if [ -z "$INCLUDE_PATH" ]; then echo "File lib*.so was not found"; exit 1; fi ;
+      fi ;
+    fi
+
+before_script:
+  - if [ -n "$DB" ]; then
+      export DBD_MYSQL_TESTUSER=msandbox ;
+      export DBD_MYSQL_TESTPASSWORD=msandbox ;
+      export DBD_MYSQL_TESTHOST=127.0.0.1 ;
+      export DBD_MYSQL_TESTPORT=3310 ;
+    elif [ -n "$CONC_DB" ]; then
+      export DBD_MYSQL_TESTHOST=127.0.0.1 ;
+      export DBD_MYSQL_TESTPORT=3306 ;
+    fi
+  - if [ -n "$CONC_DB" ]; then
+      if [ -x $HOME/conc/bin/mysql_config ]; then
+        export DBD_MYSQL_CONFIG="$HOME/conc/bin/mysql_config" ;
+      else
+        export DBD_MYSQL_CFLAGS="-I`dirname $INCLUDE_PATH`" ;
+        export DBD_MYSQL_LIBS="-L`dirname $LIB_PATH` -l`echo $LIB_PATH | sed 's/.*\/lib//;s/\.so//'`" ;
+        export DBD_MYSQL_CONFIG="skip" ;
+      fi ;
+    elif [ -n "$DB" ]; then
+      export DBD_MYSQL_CONFIG="$SANDBOX_HOME/msb/my sql_config" ;
+    else
+      export DBD_MYSQL_FORCE_EMBEDDED=1 ;
+    fi
+  - export HARNESS_OPTIONS=j1
+  - export RELEASE_TESTING=1
+  - export CONNECTION_TESTING=1
+  - export SKIP_CRASH_TESTING=1
+
+script:
+  - rm -f t/mysql.mtest
+  - perl Makefile.PL
+  - make disttest
